## 1 导入

In [1]:
import numpy as np

## 2 version and config

In [2]:

print(np.version)

<module 'numpy.version' from 'D:\\ProgramData\\Anaconda3\\lib\\site-packages\\numpy\\version.py'>


In [3]:
np.show_config()

mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\lib', 'D:/ProgramData/Anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['D:/ProgramData/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2016.4.246\\windows\\mkl\\lib', 'D:/P

## 3 创建空向量

In [4]:
Z=np.zeros(15)# length=15

In [5]:
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


## 4 数组内存大小

In [6]:
Z=np.zeros((10,10))

In [7]:
Z

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [8]:
Z.size

100

In [9]:
Z.itemsize

8

In [10]:
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


## 5命令行得到numpy中add函数的说明文档

In [11]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.  If ``x1.shape != x2.shape``, they must be
    broadcastable to a common shape (which may be the shape of one or
    the other).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or `None`,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    Values of True indicate to calculate the ufunc at that position, values
    of False indicate to leave the value in the output alone.
**kwargs
    For other keyword-only arguments, see the
    :ref:`ufunc docs <ufuncs.kwargs>`.

Returns
-------
add : ndarray or scalar
    The

## 6 创建空向量 并修改特定位置的值

In [12]:
Z=np.zeros(15)
Z[6]=10
print(Z)

[ 0.  0.  0.  0.  0.  0. 10.  0.  0.  0.  0.  0.  0.  0.  0.]


## 7. 创建一个值域范围从10到49的向量

In [13]:
Z=np.arange(10,49)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


## 8. 反转一个向量(第一个元素变为最后一个)

In [14]:
Z=Z[::-1]

In [15]:
Z

array([48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
       31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15,
       14, 13, 12, 11, 10])

## 9. 创建一个 3x3 并且值从0到8的矩阵

In [16]:
Z=np.arange(9)
print(Z)

[0 1 2 3 4 5 6 7 8]


In [17]:
Z=Z.reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 10. 找到数组[1,2,0,0,4,0]中非0元素的位置索引

In [18]:
Z=[1,2,0,0,4,0]

In [19]:
print(np.nonzero(Z))

(array([0, 1, 4], dtype=int64),)


In [20]:
Z=[1,2,0,0,"4",0]

In [21]:
print(np.nonzero(Z))

(array([0, 1, 2, 3, 4, 5], dtype=int64),)


## 11. 创建一个 3x3 的单位矩阵 

In [22]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## 12. 创建一个 3x3x3的随机数组

In [23]:
Z = np.random.random((3,3,3))

In [24]:
Z

array([[[0.20470408, 0.32531847, 0.23468816],
        [0.34396177, 0.44499343, 0.30070493],
        [0.25369824, 0.28382171, 0.60780723]],

       [[0.85428107, 0.19886102, 0.35554745],
        [0.38359897, 0.83654007, 0.06104317],
        [0.84744467, 0.51847263, 0.21129503]],

       [[0.94965109, 0.92597367, 0.27759544],
        [0.11928759, 0.29476018, 0.96781144],
        [0.81954844, 0.8165592 , 0.83170512]]])

## 13. 创建一个 10x10 的随机数组并找到它的最大值和最小值

In [25]:
Z= np.random.random((10,10))

In [26]:
print(Z.min(),Z.max())

0.0013960128939333183 0.9936722422179148


## 14. 创建一个长度为30的随机向量并找到它的平均值 

In [27]:
Z=np.random.random((30))
print(Z)

[0.22210776 0.05112883 0.25728554 0.25155613 0.59313492 0.72646794
 0.44097486 0.42905801 0.98416195 0.79840189 0.59350638 0.04521973
 0.57040514 0.42147522 0.72091291 0.75983192 0.91362819 0.25400032
 0.86709355 0.32713789 0.15697526 0.44367952 0.49433805 0.12828789
 0.26530429 0.69710865 0.29217165 0.6675695  0.40306469 0.79956505]


In [28]:
print(Z.mean())

0.48585178776441623


## 15. 创建一个二维数组，其中边界值为1，其余值为0 

In [29]:
Z= np.ones((10,10))
Z[1:-1,1:-1]=0

In [30]:
Z

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

## 16. 对于一个存在在数组，如何添加一个用0填充的边界?

In [31]:
Z=np.ones((5,5))
print(Z)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [32]:
Z = np.pad(Z, pad_width=(1), mode='constant', constant_values=0)

In [33]:
Z

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

## 17. 以下表达式运行的结果分别是什么?

In [34]:
print(0 * np.nan,
np.nan == np.nan,
np.inf > np.nan,
np.nan - np.nan,
0.3 == 3 * 0.1)

nan False False nan False


## 18. 创建一个 5x5的矩阵，并设置值1,2,3,4落在其对角线下方位置

In [35]:
1+np.arange(4)

array([1, 2, 3, 4])

In [36]:
Z = np.diag(np.arange(1,5),k=-1)
Z

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

## 19. 创建一个8x8 的矩阵，并且设置成棋盘样式

In [37]:
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


## 20. 考虑一个 (6,7,8) 形状的数组，其第100个元素的索引(x,y,z)是什么?

In [38]:
Z=np.random.random((6,7,8))

In [39]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


In [40]:
help(np.unravel_index)

Help on built-in function unravel_index in module numpy.core.multiarray:

unravel_index(...)
    unravel_index(indices, dims, order='C')
    
    Converts a flat index or array of flat indices into a tuple
    of coordinate arrays.
    
    Parameters
    ----------
    indices : array_like
        An integer array whose elements are indices into the flattened
        version of an array of dimensions ``dims``. Before version 1.6.0,
        this function accepted just one index value.
    dims : tuple of ints
        The shape of the array to use for unraveling ``indices``.
    order : {'C', 'F'}, optional
        Determines whether the indices should be viewed as indexing in
        row-major (C-style) or column-major (Fortran-style) order.
    
        .. versionadded:: 1.6.0
    
    Returns
    -------
    unraveled_coords : tuple of ndarray
        Each array in the tuple has the same shape as the ``indices``
        array.
    
    See Also
    --------
    ravel_multi_index
    

## 21. 用tile函数去创建一个 8x8的棋盘样式矩阵

In [41]:
help(np.tile)

Help on function tile in module numpy.lib.shape_base:

tile(A, reps)
    Construct an array by repeating A the number of times given by reps.
    
    If `reps` has length ``d``, the result will have dimension of
    ``max(d, A.ndim)``.
    
    If ``A.ndim < d``, `A` is promoted to be d-dimensional by prepending new
    axes. So a shape (3,) array is promoted to (1, 3) for 2-D replication,
    or shape (1, 1, 3) for 3-D replication. If this is not the desired
    behavior, promote `A` to d-dimensions manually before calling this
    function.
    
    If ``A.ndim > d``, `reps` is promoted to `A`.ndim by pre-pending 1's to it.
    Thus for an `A` of shape (2, 3, 4, 5), a `reps` of (2, 2) is treated as
    (1, 1, 2, 2).
    
    Note : Although tile may be used for broadcasting, it is strongly
    recommended to use numpy's broadcasting operations and functions.
    
    Parameters
    ----------
    A : array_like
        The input array.
    reps : array_like
        The number of rep

In [42]:
a = np.array([[0,1],[1,0]])

In [43]:
np.tile(a,(4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

## 22. 对一个5x5的随机矩阵做归一化

In [44]:
Z=np.random.random((5,5))

In [45]:
Z

array([[0.62796426, 0.02049393, 0.02698618, 0.86322962, 0.24846084],
       [0.49545652, 0.9781896 , 0.2256247 , 0.80724407, 0.9533207 ],
       [0.85084166, 0.00221309, 0.16307202, 0.9269868 , 0.65577284],
       [0.98769992, 0.36716935, 0.12277325, 0.35255531, 0.72387432],
       [0.03966115, 0.0809596 , 0.78126667, 0.25731061, 0.10266979]])

In [46]:
Z-1

array([[-0.37203574, -0.97950607, -0.97301382, -0.13677038, -0.75153916],
       [-0.50454348, -0.0218104 , -0.7743753 , -0.19275593, -0.0466793 ],
       [-0.14915834, -0.99778691, -0.83692798, -0.0730132 , -0.34422716],
       [-0.01230008, -0.63283065, -0.87722675, -0.64744469, -0.27612568],
       [-0.96033885, -0.9190404 , -0.21873333, -0.74268939, -0.89733021]])

In [47]:
ZMAX,ZMIN=Z.max(),Z.min()

In [48]:
Z=(Z-ZMIN)/(ZMAX-ZMIN)

In [49]:
Z

array([[0.63496655, 0.01855006, 0.02513792, 0.87369664, 0.24987422],
       [0.50050739, 0.99034963, 0.22670177, 0.8168866 , 0.96511449],
       [0.86112625, 0.        , 0.16322788, 0.93839277, 0.66318466],
       [1.        , 0.37033094, 0.12233564, 0.35550168, 0.73228907],
       [0.03799955, 0.0799062 , 0.79052663, 0.25885432, 0.10193612]])

## 23. 创建一个将颜色描述为(RGBA)四个无符号字节的自定义dtype？

In [50]:
color = np.dtype([("r", np.ubyte, 1),
                   ("g", np.ubyte, 1),
                   ("b", np.ubyte, 1),
                   ("a", np.ubyte, 1)])


In [51]:
color

dtype([('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')])

## 24. 一个5x3的矩阵与一个3x2的矩阵相乘，实矩阵乘积是什么？

In [52]:
Z=np.dot(np.ones((5,3)),np.ones((3,2)))

In [53]:
Z

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

## 25. 给定一个一维数组，对其在3到8之间的所有元素取反

In [54]:
 Z = np.arange(11)
Z[(3 < Z) & (Z <= 8)] *= -1
 print(Z)


[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


## 26. 运行 

In [63]:
z=[0,1,2,3,4]

In [64]:
print(z)

[0, 1, 2, 3, 4]


In [65]:
sum(z,4)
#这个就相当于把z所有元素加起来再加一个4

14

In [67]:
np.sum(z,-1)

10

### 这个np.sum的求和相当于对矩阵进行压缩
### 第一个参数是要参与求和压缩的变量：向量/数组/矩阵。
### 第二个则决定求和的方式：1.None，2.整数， 3.整数元组。有这三种方式

In [74]:
Z=np.arange(1,7).reshape((3,2))
print(Z)

[[1 2]
 [3 4]
 [5 6]]


### 1.当求和方式为none,相当于把所有元素加成一个数

In [73]:
A=np.sum(Z)
print(A)

21


### 2.当求和方式为整数时，相当于选择一个轴向进行相加，简单的说：压缩行还是压缩列

In [76]:
B=np.sum(Z,0)
print(B)

[ 9 12]


In [77]:
C=np.sum(Z,1)
print(C)

[ 3  7 11]


In [87]:
D=np.sum(Z,-2)
print(D)

[ 9 12]


当axis为0时,是压缩行,即将每一列的元素相加,将矩阵压缩为一行
当axis为1时,是压缩列,即将每一行的元素相加,将矩阵压缩为一列
但取值不能超过数组的维度

## 27. 考虑一个整数向量Z,下列表达合法的是哪个?

In [88]:
Z=np.arange(5)

In [89]:
Z**Z


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [90]:
2 << Z >> 2


array([0, 1, 2, 4, 8], dtype=int32)

In [91]:
Z <- Z


array([False, False, False, False, False])

In [92]:
1j*Z


array([0.+0.j, 0.+1.j, 0.+2.j, 0.+3.j, 0.+4.j])

In [93]:
Z/1/1


array([0., 1., 2., 3., 4.])

In [94]:
Z<Z>Z

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

## 28

In [95]:
print(np.array(0) / np.array(0))

nan


D:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


In [96]:
print(np.array(0) // np.array(0))

0


D:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in floor_divide
  """Entry point for launching an IPython kernel.


In [97]:
print(np.array([np.nan]).astype(int).astype(float))

[-2.14748365e+09]


## 29. 如何从零位对浮点数组做舍入 ?

In [100]:
Z = np.random.uniform(-10,+10,10)


In [101]:
Z

array([-8.1138649 , -8.02689423,  6.46076714, -7.58533842, -0.74965271,
       -2.64620164,  4.13883271,  2.45522515,  3.32716457, -1.88415187])

In [102]:
print (np.copysign(np.ceil(np.abs(Z)), Z))

[-9. -9.  7. -8. -1. -3.  5.  3.  4. -2.]


## 30. 如何找到两个数组中的共同元素?

In [104]:
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[3 6 7 8 9]


## 31. 如何忽略所有的 numpy 警告(尽管不建议这么做)?

In [108]:
# Suicide mode on
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0

# Back to sanity
_ = np.seterr(**defaults)

An equivalent way, with a context manager:

with np.errstate(divide='ignore'):
    Z = np.ones(1) / 0

SyntaxError: invalid syntax (<ipython-input-108-0437b6d2f8fa>, line 8)

32. 

In [107]:
np.sqrt(-1) == np.emath.sqrt(-1)

D:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in sqrt
  """Entry point for launching an IPython kernel.


False

## 33. 如何得到昨天，今天，明天的日期?

In [109]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print ("Yesterday is " + str(yesterday))
print ("Today is " + str(today))
print ("Tomorrow is "+ str(tomorrow))

Yesterday is 2019-08-06
Today is 2019-08-07
Tomorrow is 2019-08-08


## 34. 如何得到所有与2016年7月对应的日期？

In [110]:
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


##  35. 如何直接在位计算(A+B)\*(-A/2)(不建立副本)?

In [111]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

## 36. 用五种不同的方法去提取一个随机数组的整数部分

In [112]:
Z = np.random.uniform(0,10,10)
print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))
print (np.trunc(Z))

[8. 5. 3. 8. 5. 0. 7. 2. 4. 3.]
[8. 5. 3. 8. 5. 0. 7. 2. 4. 3.]
[8. 5. 3. 8. 5. 0. 7. 2. 4. 3.]
[8 5 3 8 5 0 7 2 4 3]
[8. 5. 3. 8. 5. 0. 7. 2. 4. 3.]


37. 创建一个5x5的矩阵，其中每行的数值范围从0到4 (★★☆)
(提示: np.arange)

In [114]:
Z = np.zeros((5,5))
Z += np.arange(5)
print (Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


38. 通过考虑一个可生成10个整数的函数，来构建一个数组(★☆☆)
(提示: np.fromiter)

In [115]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print (Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]



39. 创建一个长度为10的随机向量，其值域范围从0到1，但是不包括0和1 (★★☆)
(提示: np.linspace)

In [117]:
Z = np.linspace(0,1,11,endpoint=False)[1:]
print (Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


In [ ]:
40. 创建一个长度为10的随机向量，并将其排序 (★★☆)
(提示: sort)

In [116]:
Z = np.random.random(10)
Z.sort()
print (Z)

[0.05227205 0.32003596 0.38090536 0.4092941  0.52245008 0.53809177
 0.60044568 0.9082141  0.93529004 0.97373023]



41.对于一个小数组，如何用比 np.sum更快的方式对其求和？(★★☆)
(提示: np.add.reduce)

In [118]:
Z = np.arange(10)
np.add.reduce(Z)

45

In [119]:
# 42. 对于两个随机数组A和B，检查它们是否相等(★★☆)
# (提示: np.allclose, np.array_equal)

A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)
# 方法2
# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)

False
False


In [120]:
# 43. 创建一个只读数组(read-only) (★★☆)
# (提示: flags.writeable)

# 使用如下过程实现
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] = 1

ValueError: assignment destination is read-only

In [ ]:

44. 将笛卡尔坐标下的一个10x2的矩阵转换为极坐标形式(★★☆)
(hint: np.sqrt, np.arctan2)

# Z = np.random.random((10,2))
# X,Y = Z[:,0], Z[:,1]
# R = np.sqrt(X**2+Y**2)
# T = np.arctan2(Y,X)
# print (R)
# print (T)
45. 创建一个长度为10的向量，并将向量中最大值替换为1 (★★☆)
(提示: argmax)

# Z = np.random.random(10)
# Z[Z.argmax()] = 0
# print (Z)
46. 创建一个结构化数组，并实现 x 和 y 坐标覆盖 [0,1]x[0,1] 区域 (★★☆)
(提示: np.meshgrid)

# Z = np.zeros((5,5), [('x',float),('y',float)])
# Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
#                              np.linspace(0,1,5))
# print(Z)
47. 给定两个数组X和Y，构造Cauchy矩阵C (Cij =1/(xi - yj))
(提示: np.subtract.outer)

# X = np.arange(8)
# Y = X + 0.5
# C = 1.0 / np.subtract.outer(X, Y)
# print(np.linalg.det(C))
48. 打印每个numpy标量类型的最小值和最大值？ (★★☆)
(提示: np.iinfo, np.finfo, eps)

# for dtype in [np.int8, np.int32, np.int64]:
#     print(np.iinfo(dtype).min)
#     print(np.iinfo(dtype).max)

# for dtype in [np.float32, np.float64]:
#     print(np.finfo(dtype).min)
#     print(np.finfo(dtype).max)
#     print(np.finfo(dtype).eps)
49. 如何打印一个数组中的所有数值? (★★☆)
(提示: np.set_printoptions)

# np.set_printoptions(threshold=np.nan)
# Z = np.zeros((16,16))
# print (Z)
50. 给定标量时，如何找到数组中最接近标量的值？(★★☆)
(提示: argmin)

# Z = np.arange(100)
# v = np.random.uniform(0,100)
# index = (np.abs(Z-v)).argmin()
# print (Z[index])

我，写不下去了最后几个，所花时间还是有点多。但是重点是这些题的设置没有主次，并不是根据由浅入深，或者常用来设置的。我觉得这对于新手很不友好。